In [1]:
import numpy as np

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 10, 12]])
print(a[0])
print("a =", a)

[1 2 3 4]
a = [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 10 12]]


In [3]:
import numpy as np

# Create Array filled with zeros
b = np.zeros(4)
print("b =", b)

b = [0. 0. 0. 0.]


In [17]:
import numpy as np

# Create Array filled with 2x ones
c = np.ones(2)
print("c =", c)

c = [1. 1.]


In [4]:
import numpy as np

# Creates an array with 
# initial random content
# based on the state of memory

d = np.empty(3)
print("d =", d)

d = [1.66043036e+243 1.96086552e+243 1.39310750e-258]


In [5]:
import numpy as np

# Range from 0 upto (not including)
e = np.arange(5)
print("e =", e)

e = [0 1 2 3 4]


In [18]:
import numpy as np

#   Array of evenly inter-spaced values
#   start at 1st value,
#   Upto but not including the second value
#   By steps of the last value

f = np.arange(2, 9, 2)
print("f =", f)

f = [2 4 6 8]


In [8]:
import numpy as np

# With values spaced linearly 
# from 1st value
# up to 2nd value
# with X number of elements

g = np.linspace(0, 10, num=5)
print("g =", g)

g = [ 0.   2.5  5.   7.5 10. ]


In [9]:
import numpy as np

# Sorting array elements
arr1 = np.array([2, 1, 5, 3, 7, 4, 6, 8])
a1 = np.sort(arr1)
print("a1 =", a1)

a1 = [1 2 3 4 5 6 7 8]


In [14]:
import numpy as np

# Concatenating 2 Arrays
a2 = np.array([1, 2, 3, 4])
b2 = np.array([5, 6, 7, 8])
arr2 = np.concatenate((a2, b2))
print("arr2 =", arr2)


arr2 = [1 2 3 4 5 6 7 8]


In [15]:
import numpy as np

# Concatenating more Arrays
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
arr3 = np.concatenate((x, y), axis=0)
print("arr3", arr3)

arr3 [[1 2]
 [3 4]
 [5 6]]


In [16]:
import numpy as np

# Discovering the shape and size of an Array
array_example = np.array(
    [
        [[0, 1, 2, 3], [4, 5, 6, 7]],
        [[0, 1, 2, 3], [4, 5, 6, 7]],
        [[0, 1, 2, 3], [4, 5, 6, 7]],
    ]
)

# Number of Dimensions
t = array_example.ndim
print("Dimension =", t)

# Array Size
u = array_example.size
print("Size =", u)

# Array Shape
v = array_example.shape
print("Shape =", v)


Dimension = 3
Size = 24
Shape = (3, 2, 4)


In [19]:
import numpy as np

# Reshaping arrays

# First create an array of 6 elements
h = np.arange(6)
print("Original array h ... ", h)

# reshape into 3 axis w/ length of 2
i = h.reshape(3, 2)
print("Reshaped array ...", i)


Original array h ...  [0 1 2 3 4 5]
reshaped array ... [[0 1]
 [2 3]
 [4 5]]


In [21]:
import numpy as np

#   Indexing and Slicing Arrays ...
data = np.array([1, 2, 3])
aa2 = data[1]
bb2 = data[0:2]
cc2 = data[1:]
dd2 = data[-2:]
print("Original array ...", data)
print("Element [2] ...", aa2)
print("Slice 0:2 ...", bb2)
print("Slice [1:] ...", cc2)
print("Slice [-2:] ...", dd2)


Original array ... [1 2 3]
Element [2] ... 2
Slice 0:2 ... [1 2]
Slice [1:] ... [2 3]
Slice [-2:] ... [2 3]


In [23]:
import numpy as np

# More Indexing and Slicing
data2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Original array ...", data2)
print("Elements < 5 ...", data2[data2 < 5])

five_up = data2 >= 5
print("Elements >= 5 ...", data2[five_up])

divisible_by_2 = data2[data2 % 2 == 0]
print("Elements divisible by 2 ...", divisible_by_2)


Original array ... [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Elements < 5 ... [1 2 3 4]
Elements >= 5 ... [ 5  6  7  8  9 10 11 12]
Elements divisible by 2 ... [ 2  4  6  8 10 12]


In [25]:
import numpy as np

# BROADCASTING ARRAYS

# Create a (3, 4) shape-array
x = np.array(
    [[-0.0, -0.1, -0.2, -0.3], [-0.4, -0.5, -0.6, -0.7], [-0.8, -0.9, -1.0, -1.1]]
)
# Create a (4,) shape-array
y = np.array([1, 2, 3, 4])

# multiplying (4,) array -- y
# by (3, 4) array -- x
# Y multiplied by each row of X
print("X * Y = ", x * y)

#   Output: -
#   array([ [-0. , -0.2, -0.6, -1.2],
#        	[-0.4, -1. , -1.8, -2.8],
#        	[-0.8, -1.8, -3. , -4.4] ])


X * Y =  [[-0.  -0.2 -0.6 -1.2]
 [-0.4 -1.  -1.8 -2.8]
 [-0.8 -1.8 -3.  -4.4]]
